import { getCountryName } from '@/lib/countries'
import { fetchRssArticles, type RssArticle } from '@/lib/rss'
import type { NewsItem } from '@/types/news'
import { recordTokenUsage } from '@/lib/cache'
import { matchKeywords } from '@/lib/keywords/match'

interface SummarizedItem {
  originalIndex: number
  category: string
  summary: string
  detail: string
  sentiment: 'positive' | 'neutral' | 'negative'
  keywords?: string[]
}

interface OpenAIResponse {
  choices: { message: { content: string | null } }[]
  usage?: { prompt_tokens: number; completion_tokens: number }
}

export function simpleHash(str: string): string {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash + str.charCodeAt(i)) | 0
  }
  return Math.abs(hash).toString(36)
}

const LANG_LABELS: Record<string, string> = {
  en: 'English',
  ko: 'Korean',
}

const CATEGORY_PROMPT = `Assign one category per article from this list:
Politics, Economy, Society, Tech, Defense, Diplomacy, Environment, Health, Culture

Exclude: celebrity/idol news (concerts, tours, comebacks, fan events, dating), K-pop, movie/TV/drama reviews, sports scores/match results.
General sports INDUSTRY news (e.g. league deals, stadium economics) is OK.`

/** RSS description이 이 길이 미만이면 LLM에 보내지 않고 drop.
 *  짧은 입력으로는 신뢰할 수 있는 요약을 만들 수 없음. */
const MIN_DESCRIPTION_LENGTH = 200

async function callOpenAI(messages: { role: string; content: string }[]): Promise<OpenAIResponse> {
  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) throw new Error('Missing OPENAI_API_KEY')

  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      temperature: 0.3,
      response_format: { type: 'json_object' },
      messages,
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`OpenAI API error: ${res.status} ${err}`)
  }

  return res.json()
}

/**
 * Google News RSS에서 기사 수집 (무료) + OpenAI로 요약만 수행
 */
export async function fetchNews(countryCode: string, lang = 'en'): Promise<NewsItem[]> {
  const articles = await fetchRssArticles(countryCode)
  return fetchNewsFromArticles(countryCode, lang, articles)
}

/**
 * Summarize pre-collected articles with OpenAI (no RSS fetch)
 */
export async function fetchNewsFromArticles(countryCode: string, lang = 'en', articles: RssArticle[]): Promise<NewsItem[]> {
  const countryName = getCountryName(countryCode)
  const langLabel = LANG_LABELS[lang] ?? 'English'
  const now = new Date().toISOString()

  if (articles.length === 0) {
    return []
  }

  const filteredArticles = articles.filter((a) => (a.description?.length ?? 0) >= MIN_DESCRIPTION_LENGTH)
  if (filteredArticles.length === 0) {
    return []
  }

  if (filteredArticles.length < articles.length) {
    console.log(`[news] ${countryCode}: filtered ${articles.length - filteredArticles.length} short articles (<${MIN_DESCRIPTION_LENGTH}c), kept ${filteredArticles.length}`)
  }

  const articlesForAi = filteredArticles.map((a, i) => ({
    i,
    // `t` is context for relevance classification only. The model never
    // returns or controls the displayed headline; that always comes from RSS.
    t: a.title,
    d: a.description.slice(0, 2000),
  }))

  const response = await callOpenAI([
    {
      role: 'system',
      content: `You filter and summarize news articles that are DIRECTLY about ${countryName}. Return JSON: {"items":[...]}

FILTERING RULE:
- Include articles that are significantly about ${countryName} — domestic affairs, economy, politics, or international relations involving ${countryName}
- EXCLUDE articles that only mention ${countryName} in passing while being primarily about a different country
- Articles about bilateral relations are fine if ${countryName} is one of the main parties
- Articles may be in any language — translate only the summary and detail to ${langLabel}.
- NEVER return a title. Headlines are source records and are not generated by this system.

Each item: {"originalIndex":number,"category":"one of the categories below","summary":"1-2 sentence ${langLabel} summary","detail":"${langLabel} translation of the RSS description","sentiment":"positive"|"neutral"|"negative","keywords":["slug1","slug2",...]}

DETAIL FIELD:
- "detail" is a faithful ${langLabel} translation of the RSS description. Do not expand, explain, infer, or add context. Preserve uncertainty and attribution from the input.
- If the input does not state a fact, it must not appear in either summary or detail.

CRITICAL: Use only information actually present in the input title and description. Do not invent or add historical context, implications, predictions, "what to watch" remarks, stakeholder analysis, names, numbers, dates, locations, or quotes. "summary" is a brief 1-2 sentence overview. "detail" must never be empty.

For "keywords": extract 3-5 canonical English slug keywords (lowercase kebab-case ASCII).
Prefer named entities — people, countries, organizations, companies — and concrete topics.
Skip generic words (news, today, world, breaking). Use English slugs even if the article is in Korean.

${CATEGORY_PROMPT}

Include all relevant articles (up to 40).`,
    },
    {
      role: 'user',
      content: JSON.stringify(articlesForAi),
    },
  ])

  if (response.usage) {
    await recordTokenUsage(response.usage.prompt_tokens, response.usage.completion_tokens, countryCode, 'rss')
  }

  const content = response.choices[0]?.message?.content
  if (!content) return []

  const parsed = JSON.parse(content)

  if (!parsed.items || !Array.isArray(parsed.items)) return []

  const validItems = (parsed.items as SummarizedItem[])
    .filter((item) => typeof item.originalIndex === 'number' && item.originalIndex >= 0 && item.originalIndex < filteredArticles.length)
    // detail must be non-empty — empty detail means LLM either misfired or
    // refused to translate, so the row isn't trustworthy enough to cache.
    .filter((item) => typeof item.detail === 'string' && item.detail.trim().length > 0)

  if (validItems.length < parsed.items.length) {
    const dropped = parsed.items.length - validItems.length
    console.log(`[news] ${countryCode}: dropped ${dropped} articles (invalid index or empty detail)`)
  }

  return validItems
    .map((item) => {
      const original: RssArticle = filteredArticles[item.originalIndex]
      // Normalize free-form LLM keywords against the curated vocabulary.
      // Unknown keywords are dropped here; pending-curator queue is Phase 3.
      const rawKeywords = Array.isArray(item.keywords) ? item.keywords : []
      const { matched } = matchKeywords(rawKeywords)
      const keywords = matched.map((m) => m.slug)
      return {
        id: `${countryCode}-${simpleHash(original.link)}`,
        country: countryCode,
        category: item.category,
        // The displayed title is immutable source data. Do not substitute any
        // LLM-generated text here: it can look like article body and creates a
        // false claim that the publisher never made.
        title: original.title,
        summary: item.summary,
        detail: item.detail,
        sentiment: item.sentiment,
        source: original.source,
        url: original.link,
        pubDate: original.pubDate || now,
        cachedAt: now,
        isRealtime: true,
        keywords,
      }
    })
}
